### ISSUE TITLE
Override `redirect_to` to use a 303 for redirects after a POST request

### ISSUE THREAD

**Issue by sebastian-schuth** [betterdoc-org/general-gem-betterdoc-containerservice#28]
> As far as I can see, at least Rails uses a 302 for redirect, even after POST: https://apidock.com/rails/v6.0.0/ActionController/Redirecting/redirect_to
> 
> This mean we need to tell people to always use a 303 response code after a POST manually if they want their CS to function, right?
> 
> What about [betterdoc-org/patient-cs-facts#18](https://github.com/betterdoc-org/patient-cs-facts/pull/18) ? Will you submit this as PR, or was it just a test?

I think it should be easy to change rails default (overwrite redirect_to to use 303 by default)

_Originally posted by @vlado in https://github.com/betterdoc-org/stacker/pull/350#issuecomment-630787021_

**Comment by sebastian-schuth** [comment]
@vlado to get this right, ew need to make sure that the 303 is only used to generate a response for POST requests -- otherwise all redirects will be 303s, and I am not sure this is what we want.

**Comment by vlado** [comment]
@sebastian-schuth ok, I can investigate this. I suppose we have access to request object in original method so we should be able to detect POST requests.

I'll take a look at the source and find a best way to do this.
