### ISSUE TITLE
Deploy gem to github package registry

### ISSUE THREAD

**Issue by sebastian-schuth** [betterdoc-org/general-gem-betterdoc-containerservice#4]
This would be a good thing to try out the package repository.

https://help.github.com/en/articles/configuring-rubygems-for-use-with-github-package-registry

**Comment by sebastian-schuth** [comment]
Also a good candidate for a Friday project

**Comment by cseifert-betterdoc** [comment]
Closing as 1) this is the old containerservice repository and 2) we have the pipeline for publishing the Gem setup correctly for the new repository.
