### ISSUE TITLE
Make sure gem works with Rails 6

### ISSUE THREAD

**Issue by vlado** [betterdoc-org/general-gem-betterdoc-containerservice#5]
While trying to add this gem to medic-cs-clinics which is running on Rails 6 I got an error.

![Screenshot 2019-06-27 14 24 35](https://user-images.githubusercontent.com/5148/60266344-27dadc00-98e8-11e9-9baa-fb870dd379ad.png)

**Comment by cseifert-betterdoc** [comment]
Closing this as 1) this is the old repository and 2) the new repository works correctly with Rails 6
